db:
  client: mysql2
  user: creds
  password: creds
  host: creds
  database: tiger
  timezone: Z

listen:
  http:
    port: 3001
    keep_alive_timeout_seconds: 90
    headers_timeout_seconds: 120

upload:
  image:
    dir: /public/image
    path: /image

sighting:
  radius_in_km: 5
